#ifndef GPIO_CONFIG_H
#define GPIO_CONFIG_H


// Output Pins
#define LCD_RS_PIN 8
#define LCD_EN_PIN 9
#define LCD_D0_PIN 4
#define LCD_D1_PIN 5
#define LCD_D2_PIN 6
#define LCD_D3_PIN 7

#define BUZZER_OUTPUT_PIN LED_BUILTIN


// Control Pins

#define HOT_WATER_INLET_VALVE_RELAY_OUTPUT_PIN D4
#define COLD_WATER_INLET_VALVE_RELAY_OUTPUT_PIN D5

#define WATER_DRAIN_VALVE_RELAY_OUTPUT_PIN D6
// #define NA_RELAY_OUTPUT_PIN 13

#define CLOCKWISE_SPINNER_POWER_RELAY_OUTPUT_PIN D7
#define ANTICLOCKWISE_SPINNER_POWER_RELAY_OUTPUT_PIN D8


// Input Pins

#define LID_INPUT_PIN D2
#define HOLD_SKIP_INPUT_PIN D3

#define KEYPAD_SHIELD_INPUT_PIN D1




#endif